// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hjxyietnrsatxrrbfyps.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhqeHlpZXRucnNhdHhycmJmeXBzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzOTI0OTIsImV4cCI6MjA1OTk2ODQ5Mn0.opYimrTMuwG-eCUOIOnLU68jhELacHimB2sJCVSqtYs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);